'use client';
import Link from 'next/link';
import {Bike,MapPin,Clock3,CreditCard,Phone,Mail,ArrowUpRight,Camera,ShoppingBag} from 'lucide-react';
import {SocialIcon} from './icons';
import {useShop} from './shop-provider';
export function InfoPage({kind}:{kind:'delivery'|'contacts'|'privacy'}){const {t,config}=useShop();
 if(kind==='privacy')return <div className="container page-wrap"><div className="page-heading"><span className="eyebrow">WATTA SUSHI</span><h1>{t.privacyTitle}</h1><p>{t.privacyText}</p><p>{t.cookie}</p><a href={`mailto:${config.email}`}>{config.email}</a></div></div>;
 return <div className="container page-wrap"><div className="page-heading"><span className="eyebrow">WATTA SUSHI / AMSTERDAM</span><h1>{kind==='delivery'?t.deliveryTitle:t.contactTitle}</h1><p>{kind==='delivery'?t.deliveryText:t.contactText}</p></div>{kind==='delivery'?<div className="info-grid"><div className="info-card"><Bike/><h2>{t.area}</h2><p>{t.areaText}</p><p>{t.routeTerms}</p></div><div className="info-card"><ShoppingBag/><h2>{t.feesTitle}</h2><p>{t.deliveryRate}</p><p>{t.minimumRolls}</p><p>{t.pickupFree}</p></div><div className="info-card"><MapPin/><h2>{t.pickupTitle}</h2><p>Helicopterstraat 20<br/>Amsterdam, Netherlands</p><a className="text-link" target="_blank" rel="noreferrer" href="https://www.google.com/maps/search/?api=1&query=Helicopterstraat+20+Amsterdam">{t.map}<ArrowUpRight size={17}/></a></div><div className="info-card"><CreditCard/><h2>{t.paymentTitle}</h2><p>{t.paymentText}</p><p>{t.paymentMethods}</p></div><div className="info-card"><Clock3/><h2>{t.timing}</h2><p>{t.daily} 14:00–21:00</p><p>{t.timingText}</p></div><div className="info-card"><Phone/><h2>{t.allergy}</h2><p>{t.allergyText}</p><a className="text-link" href={`tel:${config.phone}`}>+31 6 4932 6549<ArrowUpRight size={17}/></a></div></div>:<><div className="info-grid"><div className="info-card"><Phone/><h2>{t.call}</h2><a className="text-link" href={`tel:${config.phone}`}>+31 6 4932 6549<ArrowUpRight size={17}/></a><p>{t.daily} 14:00–21:00</p></div><div className="info-card"><Mail/><h2>{t.write}</h2><a className="text-link" href={`mailto:${config.email}`}>{config.email}<ArrowUpRight size={17}/></a></div><div className="info-card"><MapPin/><h2>{t.pickupTitle}</h2><p>Helicopterstraat 20<br/>Amsterdam, Netherlands</p><a className="text-link" href="https://www.google.com/maps/search/?api=1&query=Helicopterstraat+20+Amsterdam" target="_blank" rel="noreferrer">{t.map}<ArrowUpRight size={17}/></a></div><div className="info-card"><Camera/><h2>{t.social}</h2><div className="social-links"><a href="https://www.instagram.com/watta_sushi/" target="_blank" rel="noreferrer" aria-label="Instagram"><SocialIcon name="Instagram"/></a><a href="https://www.tiktok.com/@watta.sushi" target="_blank" rel="noreferrer" aria-label="TikTok"><SocialIcon name="TikTok"/></a><a href="https://t.me/wattasushiwork" target="_blank" rel="noreferrer" aria-label="Telegram"><SocialIcon name="Telegram"/></a></div></div></div><div className="map-panel"><iframe loading="lazy" referrerPolicy="no-referrer-when-downgrade" title="Helicopterstraat 20, Amsterdam" src="https://maps.google.com/maps?q=Helicopterstraat%2020%20Amsterdam&t=&z=15&ie=UTF8&iwloc=&output=embed"/></div></>}<Link className="button" href="/menu" style={{marginTop:30}}>{t.viewMenu}<ArrowUpRight size={18}/></Link></div>;
}
