'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {useEffect,useRef} from 'react';
import {ArrowUpRight,ArrowRight,ShoppingBag,Clock3,MapPin,Phone,Camera,X,Plus,Minus,Trash2,LockKeyhole} from 'lucide-react';
import {LanguageSwitcher} from './language-switcher';
import {SocialIcon} from './icons';
import {useShop} from './shop-provider';
import {money,products} from '@/lib/catalog';
export function Brand(){return <Link href="/" className="brand" aria-label="Watta Sushi — home"><span className="brand-crop"><img src="/brand/wordmark.png" alt="Watta Sushi" width="660" height="660" /></span></Link>;}
export function Header(){const {t,locale,count,subtotal,setCartOpen}=useShop();const path=usePathname();return <>
 <div className="topbar"><div className="container topbar-inner"><span><MapPin size={13}/> Helicopterstraat 20, Amsterdam</span><span><Clock3 size={13}/>{t.daily} 14:00–21:00</span><a href="tel:+31649326549"><Phone size={13}/> +31 6 4932 6549</a></div></div>
 <header className="header"><div className="container header-inner"><Brand/><nav className="main-nav" aria-label="Main navigation"><Link className={path==='/'||path==='/menu'?'active':''} href="/menu">{t.menu}</Link><Link className={path==='/delivery'?'active':''} href="/delivery">{t.delivery}</Link><Link className={path==='/contacts'?'active':''} href="/contacts">{t.contacts}</Link></nav><div className="header-actions"><LanguageSwitcher/><button className="cart-button" onClick={()=>setCartOpen(true)} aria-label={`${t.cart}: ${count}`}><ShoppingBag size={19}/><span className="cart-price">{money(subtotal,locale)}</span><span className="cart-count">{count}</span></button></div></div></header>
 </>;}
export function Footer(){const {t}=useShop();return <footer className="footer"><div className="container footer-grid"><div><Brand/><p className="footer-tagline">{t.footerLine}</p><div className="social-links"><a href="https://www.instagram.com/watta_sushi/" target="_blank" rel="noreferrer" aria-label="Instagram"><SocialIcon name="Instagram"/></a><a href="https://www.tiktok.com/@watta.sushi" target="_blank" rel="noreferrer" aria-label="TikTok"><SocialIcon name="TikTok"/></a><a href="https://t.me/wattasushiwork" target="_blank" rel="noreferrer" aria-label="Telegram"><SocialIcon name="Telegram"/></a></div></div><div><h3>{t.contacts}</h3><a href="tel:+31649326549">+31 6 4932 6549</a><a href="mailto:Info@wattaholding.nl">Info@wattaholding.nl</a><p>Helicopterstraat 20<br/>Amsterdam, Netherlands</p></div><div><h3>{t.hoursLabel}</h3><p>{t.daily}<br/><strong>14:00–21:00</strong></p><Link href="/delivery">{t.delivery} <ArrowUpRight size={14}/></Link></div><div className="footer-invite"><span>{t.heroTag}</span><Link href="/menu">{t.order}<ArrowUpRight size={30}/></Link></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Watta Sushi</span><Link href="/privacy">{t.privacy}</Link><span className="payment-logos">VISA <b>●●</b> iDEAL <span>Stripe</span></span></div></footer>;}
export function InstagramButton(){const {count}=useShop();return <a className={`instagram-fab${count?' with-cart':''}`} href="https://www.instagram.com/watta_sushi/" target="_blank" rel="noopener noreferrer" aria-label="Watta Sushi on Instagram" title="Instagram"><SocialIcon name="Instagram"/><span className="sr-only">Instagram</span></a>;}
export function CartLines(){const {cart,locale,t,change,remove}=useShop();return <div className="cart-lines">{cart.map(i=>{const p=products.find(p=>p.id===i.productId)!;return <div className="cart-line" key={p.id}><img src={p.image} alt="" width="84" height="84"/><div className="cart-line-info"><strong>{p.name[locale]}</strong><span>{money(p.price,locale)}</span><div className="quantity"><button aria-label={`${t.quantity} − ${p.name[locale]}`} onClick={()=>change(p.id,-1)}><Minus size={13}/></button><span>{i.quantity}</span><button disabled={i.quantity>=30} aria-label={`${t.quantity} + ${p.name[locale]}`} onClick={()=>change(p.id,1)}><Plus size={13}/></button></div></div><div className="cart-line-right"><button className="icon-button" aria-label={`${t.remove} ${p.name[locale]}`} onClick={()=>remove(p.id)}><Trash2 size={15}/></button><strong>{money(p.price*i.quantity,locale)}</strong></div></div>;})}</div>;}
export function CartDrawer(){const {cartOpen,setCartOpen,t,count,subtotal,locale,rolls,config}=useShop();const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const dialog=ref.current;if(cartOpen){dialog?.showModal();document.body.style.overflow='hidden';}else{dialog?.close();document.body.style.overflow='';}return()=>{document.body.style.overflow='';};},[cartOpen]);
 return <dialog ref={ref} className="cart-dialog" aria-labelledby="cart-title" onCancel={()=>setCartOpen(false)} onClick={e=>{if(e.target===ref.current)setCartOpen(false);}}><div className="drawer"><div className="drawer-heading"><h2 id="cart-title">{t.cart}<span>{count}</span></h2><button className="icon-button" autoFocus aria-label={t.close} onClick={()=>setCartOpen(false)}><X size={23}/></button></div>{count? <><div className="drawer-scroll"><CartLines/></div><div className="drawer-bottom"><div className="sum-row"><span>{t.subtotal}</span><strong>{money(subtotal,locale)}</strong></div><p className="small-muted">{t.deliveryRate}</p>{rolls<config.minimumRolls&&<p className="notice">{t.minimumError}</p>}<Link className="button full" href="/checkout" onClick={()=>setCartOpen(false)}>{t.checkout}<ArrowRight size={18}/></Link><p className="secure"><LockKeyhole size={13}/>{t.secure}</p></div></>:<div className="empty-cart"><ShoppingBag size={50} strokeWidth={1}/><h3>{t.empty}</h3><p>{t.emptyText}</p><Link href="/menu" className="button" onClick={()=>setCartOpen(false)}>{t.browse}<ArrowRight size={17}/></Link></div>}</div></dialog>;
}
export function MobileCart(){const {count,subtotal,locale,t,setCartOpen}=useShop();return count>0?<button className="mobile-cart" onClick={()=>setCartOpen(true)}><span><ShoppingBag size={18}/>{count}</span>{t.cart}<strong>{money(subtotal,locale)}</strong></button>:null;}
