'use client';
import {useState,useRef,useEffect} from 'react';
import Link from 'next/link';
import Image from 'next/image';
import {ArrowDown,ArrowRight,ArrowUpRight,Search,Plus,Check,Sparkles,Leaf,Bike,Heart,X} from 'lucide-react';
import {CategoryIcon} from './icons';
import {useShop} from './shop-provider';
import {products,categories,money,type Product} from '@/lib/catalog';
function ProductMedia({product:p,locale}:{product:Product;locale:'nl'|'en'|'uk'}) {
  if (p.images?.length) return <div className={`set-collage count-${p.images.length}`} role="img" aria-label={p.name[locale]}>{p.images.map((src,index)=><span key={`${src}-${index}`}><Image src={src} alt="" fill sizes="(max-width:600px) 24vw, 12vw"/></span>)}</div>;
  return <Image src={p.image} alt={p.name[locale]} fill sizes="(max-width:600px) 48vw, (max-width:1000px) 45vw, 25vw"/>;
}
export function ProductCard({product:p}:{product:Product}){const {locale,t,add,cart}=useShop();const [added,setAdded]=useState(false);const feedbackTimer=useRef<ReturnType<typeof setTimeout>|null>(null);useEffect(()=>()=>{if(feedbackTimer.current)clearTimeout(feedbackTimer.current);},[]);const quantity=cart.find(i=>i.productId===p.id)?.quantity||0;return <article className={`product-card${p.categoryId===3?' set-product':''}`}><div className={`product-image${p.images?' set-image':''}${p.categoryId===7?' drink-image':''}`}><ProductMedia product={p} locale={locale}/><div className="badges">{p.popular&&<span className="badge"><Heart size={11}/>{t.popular}</span>}{p.isNew&&<span className="badge new">{t.new}</span>}</div><span className="product-number">W / {String(p.id).padStart(3,'0')}</span></div><div className="product-body"><div className="product-title-row"><h3>{p.name[locale]}</h3>{p.meta&&<span className="product-meta">{p.meta[locale]}</span>}</div><p>{p.description[locale]}</p><div className="product-bottom"><strong>{money(p.price,locale)}</strong><button disabled={quantity>=30} className={added?'add-button added':'add-button'} aria-label={`${t.add} ${p.name[locale]}`} onClick={()=>{add(p.id);setAdded(true);if(feedbackTimer.current)clearTimeout(feedbackTimer.current);feedbackTimer.current=setTimeout(()=>setAdded(false),1300);}}><span className="add-icons" aria-hidden="true"><Plus className="add-plus" size={18}/><Check className="add-check" size={18}/></span><span className="add-label">{added?t.added:t.add}</span><span className="sr-only" role="status">{added?`${p.name[locale]}: ${t.added}`:""}</span></button></div></div></article>;}
export function Storefront({menuOnly=false}:{menuOnly?:boolean}){const {t,locale}=useShop();const [query,setQuery]=useState('');const [active,setActive]=useState(0);const [filter,setFilter]=useState<'all'|'popular'|'new'>('all');
 const availableCategories=categories.filter(c=>products.some(p=>p.categoryId===c.id));
 const visible=products.filter(p=>(filter==='all'||(filter==='popular'?p.popular:p.isNew))&&`${p.name[locale]} ${p.description[locale]}`.toLowerCase().includes(query.toLowerCase()));
 const jump=(id:number,keyboard=false)=>{setActive(id);const target=document.getElementById(id?`category-${id}`:'menu');target?.scrollIntoView({behavior:keyboard||window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});};
 return <>
 {!menuOnly&&<section className="hero"><div className="container hero-grid"><div className="hero-copy"><span className="eyebrow"><span className="status-dot"/>{t.city}</span><h1>{t.heroTop}<br/><span>{t.heroBottom}</span><svg className="hero-scribble" viewBox="0 0 290 15" aria-hidden="true"><path d="M3 10 Q135 -2 286 6 M26 14 Q140 4 254 10"/></svg></h1><p>{t.heroText}</p><a className="button hero-cta" href="#menu">{t.explore}<ArrowUpRight size={20}/></a><div className="hero-note"><span>✳</span>{t.deliveryRate}</div></div><div className="hero-art"><div className="hero-circle"/><span className="art-caption">FRESH ROLLS.<br/>HAPPY SOULS.</span><Image className="hero-food" src="/menu/21.jpg" alt={products[0].name[locale]} fill priority sizes="(max-width:800px) 100vw, 55vw"/><div className="hero-stamp">WATTA<br/><span>GOOD</span><br/>CHOICE!</div><div className="hero-product-label"><span>{products[0].name[locale]}</span><ArrowDown size={18}/></div><span className="hero-star">✳</span></div></div></section>}
 <div className="values-strip"><div className="container values-inner"><span><Leaf size={17}/>{t.fresh}</span><i>✳</i><span><Heart size={17}/>{t.made}</span><i>✳</i><span><Bike size={19}/>{t.allCity}</span><i>✳</i><span>WATTA SUSHI, WATTA MOOD</span></div></div>
 <section className={`menu-section container ${menuOnly?'menu-only':''}`} id="menu"><div className="section-heading"><div><span className="eyebrow">{t.menuEyebrow}</span><h2>{t.menuTitle}</h2><p>{t.menuIntro}</p></div><span className="menu-doodle">Watta<br/><em>choice!</em> <Sparkles size={25}/></span></div>
 <div className="menu-layout"><aside className="category-sidebar"><span className="sidebar-title">{t.menu} <span>{products.length}</span></span><nav aria-label={t.menu}><button className={active===0?'selected':''} aria-current={active===0?"true":undefined} onClick={e=>jump(0,e.detail===0)}><CategoryIcon id={0} title={t.all}/>{t.all}<ArrowUpRight size={16}/></button>{availableCategories.map(c=><button key={c.id} className={active===c.id?'selected':''} aria-current={active===c.id?"true":undefined} onClick={e=>jump(c.id,e.detail===0)}><CategoryIcon id={c.id} title={c.names[locale]}/>{c.names[locale]}<span className="category-count">{products.filter(p=>p.categoryId===c.id).length}</span></button>)}</nav><div className="sidebar-note"><Bike size={26}/><strong>{t.allCity}</strong><span>{t.deliveryRate}</span><Link href="/delivery">{t.delivery}<ArrowUpRight size={14}/></Link></div></aside>
 <div className="menu-content"><div className="menu-tools"><div className="filter-tabs">{(['all','popular','new'] as const).map(f=><button key={f} className={filter===f?'selected':''} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f==='popular'&&<Heart size={13}/>} {t[f]}</button>)}</div><div className="search-input"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.search} aria-label={t.search}/>{query&&<button className="icon-button" aria-label={t.close} onClick={()=>setQuery('')}><X size={15}/></button>}</div></div>
 {query&&visible.length===0?<p className="empty-category">{t.noResults}</p>:availableCategories.map(c=>{const group=visible.filter(p=>p.categoryId===c.id);return <section className="category-section" id={`category-${c.id}`} key={c.id}><div className="category-heading"><h3>{c.names[locale]}</h3><span>{group.length} {t.items}</span></div>{group.length?<div className="product-grid">{group.map(p=><ProductCard key={p.id} product={p}/>)}</div>:<p className="empty-category">{t.emptyCategory}</p>}</section>;})}</div></div></section>
 <section className="brand-banner container"><div className="banner-mascot"><img src="/brand/mascot.png" alt="Watta Sushi mascot" width="230" height="230"/></div><div><span className="eyebrow">WATTA SUSHI / AMSTERDAM</span><h2>{t.ourPlace}</h2><p>{t.ourPlaceText}</p></div><Link href="/contacts" className="button light">{t.contacts}<ArrowRight size={19}/></Link></section>
 </>;
}
