import type { Product } from './catalog';

const setDefaults = {
  categoryId: 3,
  popular: false,
  isNew: true,
} as const;

const drinkDefaults = {
  categoryId: 7,
  rollUnits: 0,
  popular: false,
  isNew: true,
} as const;

export const curatedProducts: Product[] = [
  {
    ...setDefaults,
    id: 301,
    name: { nl: 'Seth Salmon', en: 'Seth Salmon', uk: 'Сет Salmon' },
    description: {
      nl: 'Philadelphia met zalm, California met zalm, 4 stuks zalmnigiri',
      en: 'Philadelphia with salmon, California with salmon, 4 salmon nigiri',
      uk: 'Філадельфія з лососем, Каліфорнія з лососем, 4 нігірі з лососем',
    },
    meta: { nl: '710 g', en: '710 g', uk: '710 г' },
    price: 4000,
    image: '/menu/4.jpg',
    images: ['/menu/4.jpg', '/menu/75.jpg', '/menu/184.jpg'],
    rollUnits: 2,
    popular: true,
  },
  {
    ...setDefaults,
    id: 302,
    name: { nl: 'Mix Set', en: 'Mix Set', uk: 'Mix Set' },
    description: {
      nl: 'Philadelphia met garnaal, zalmmaki, Unagi Double Maki, Deluxe Roll met tonijn',
      en: 'Philadelphia with shrimp, salmon maki, Unagi Double Maki, Deluxe Roll with tuna',
      uk: 'Філадельфія з креветкою, макі з лососем, Unagi Double Maki, Deluxe Roll з тунцем',
    },
    meta: { nl: '1040 g', en: '1040 g', uk: '1040 г' },
    price: 4700,
    image: '/menu/21.jpg',
    images: ['/menu/21.jpg', '/menu/177.jpg', '/menu/158.jpg', '/menu/163.jpg'],
    rollUnits: 4,
    popular: true,
  },
  {
    ...setDefaults,
    id: 303,
    name: { nl: 'Set for Two', en: 'Set for Two', uk: 'Set for Two' },
    description: {
      nl: 'Deluxe met tonijn, Volcano garnaal, Philadelphia-combinatie met zalm en paling',
      en: 'Deluxe with tuna, Volcano shrimp, Philadelphia salmon and eel combo',
      uk: 'Deluxe з тунцем, Volcano з креветкою, Philadelphia-комбо з лососем і вугром',
    },
    meta: { nl: '1000 g', en: '1000 g', uk: '1000 г' },
    price: 4700,
    image: '/menu/163.jpg',
    images: ['/menu/163.jpg', '/menu/148.jpg', '/menu/4.jpg', '/menu/15.jpg'],
    rollUnits: 3,
    popular: true,
  },
  {
    ...setDefaults,
    id: 304,
    name: { nl: 'Big Corporate Set', en: 'Big Corporate Set', uk: 'Big Corporate Set' },
    description: {
      nl: '9 rollen, 72 stuks: Deluxe tonijn, Philadelphia zalm, Philadelphia mango, Baked zalm, Satisfaction tonijn, Philadelphia garnaal, Euphoria, Philadelphia paling, Unagi Double Maki',
      en: '9 rolls, 72 pcs: Deluxe tuna, Philadelphia salmon, Philadelphia mango, Baked salmon, Satisfaction tuna, Philadelphia shrimp, Euphoria, Philadelphia eel, Unagi Double Maki',
      uk: '9 ролів, 72 шт.: Deluxe з тунцем, Philadelphia з лососем, Philadelphia манго, запечений лосось, Satisfaction з тунцем, Philadelphia з креветкою, Euphoria, Philadelphia з вугром, Unagi Double Maki',
    },
    meta: { nl: '2960 g · 72 stuks', en: '2960 g · 72 pcs', uk: '2960 г · 72 шт.' },
    price: 13500,
    image: '/menu/163.jpg',
    images: ['/menu/163.jpg', '/menu/4.jpg', '/menu/5.jpg', '/menu/173.jpg', '/menu/79.jpg', '/menu/21.jpg', '/menu/78.jpg', '/menu/15.jpg', '/menu/158.jpg'],
    rollUnits: 9,
    popular: true,
  },
  {
    ...setDefaults,
    id: 305,
    name: { nl: 'Philadelphia Set', en: 'Philadelphia Set', uk: 'Philadelphia Set' },
    description: {
      nl: 'Philadelphia met paling, Philadelphia met zalm, Philadelphia met garnaal',
      en: 'Philadelphia with eel, Philadelphia with salmon, Philadelphia with shrimp',
      uk: 'Філадельфія з вугром, Філадельфія з лососем, Філадельфія з креветкою',
    },
    meta: { nl: '990 g', en: '990 g', uk: '990 г' },
    price: 4700,
    image: '/menu/15.jpg',
    images: ['/menu/15.jpg', '/menu/4.jpg', '/menu/21.jpg'],
    rollUnits: 3,
    popular: true,
  },
  {
    ...setDefaults,
    id: 306,
    name: { nl: 'Brand Set', en: 'Brand Set', uk: 'Brand Set' },
    description: {
      nl: 'Deluxe Roll, Satisfaction Roll, Philadelphia Mango, Green Dragon Eel',
      en: 'Deluxe Roll, Satisfaction Roll, Philadelphia Mango, Green Dragon Eel',
      uk: 'Deluxe Roll, Satisfaction Roll, Philadelphia Mango, Green Dragon Eel',
    },
    meta: { nl: '1230 g', en: '1230 g', uk: '1230 г' },
    price: 6400,
    image: '/menu/163.jpg',
    images: ['/menu/163.jpg', '/menu/79.jpg', '/menu/5.jpg', '/menu/80.jpg'],
    rollUnits: 4,
  },
  {
    ...setDefaults,
    id: 307,
    name: { nl: 'Trio Set', en: 'Trio Set', uk: 'Trio Set' },
    description: {
      nl: 'Philadelphia met zalm, Philadelphia met zalm en sesam, Green Roll',
      en: 'Philadelphia with salmon, Philadelphia in sesame with salmon, Green Roll',
      uk: 'Філадельфія з лососем, Філадельфія в кунжуті з лососем, Green Roll',
    },
    meta: { nl: '925 g', en: '925 g', uk: '925 г' },
    price: 4500,
    image: '/menu/4.jpg',
    images: ['/menu/4.jpg', '/menu/161.jpg', '/menu/149.jpg'],
    rollUnits: 3,
  },
  {
    ...setDefaults,
    id: 308,
    name: { nl: 'Roll Dragon Set', en: 'Roll Dragon Set', uk: 'Roll Dragon Set' },
    description: {
      nl: 'Golden Dragon, Red Dragon en Green Dragon',
      en: 'Golden Dragon, Red Dragon and Green Dragon',
      uk: 'Golden Dragon, Red Dragon і Green Dragon',
    },
    price: 5000,
    image: '/menu/113.jpg',
    images: ['/menu/113.jpg', '/menu/114.jpg', '/menu/80.jpg'],
    rollUnits: 3,
  },
  {
    ...drinkDefaults,
    id: 701,
    name: { nl: 'Coca-Cola', en: 'Coca-Cola', uk: 'Coca-Cola' },
    description: { nl: 'Original Taste', en: 'Original Taste', uk: 'Оригінальний смак' },
    meta: { nl: '0,33 l', en: '0.33 L', uk: '0,33 л' },
    price: 250,
    image: '/menu/drinks/coca-cola.png',
  },
  {
    ...drinkDefaults,
    id: 702,
    name: { nl: 'Coca-Cola Zero', en: 'Coca-Cola Zero', uk: 'Coca-Cola Zero' },
    description: { nl: 'Zero Sugar', en: 'Zero Sugar', uk: 'Без цукру' },
    meta: { nl: '0,33 l', en: '0.33 L', uk: '0,33 л' },
    price: 250,
    image: '/menu/drinks/coca-cola-zero.png',
  },
  {
    ...drinkDefaults,
    id: 703,
    name: { nl: 'Fanta', en: 'Fanta', uk: 'Fanta' },
    description: { nl: 'Orange', en: 'Orange', uk: 'Апельсин' },
    meta: { nl: '0,33 l', en: '0.33 L', uk: '0,33 л' },
    price: 250,
    image: '/menu/drinks/fanta.jpg',
  },
  {
    ...drinkDefaults,
    id: 704,
    name: { nl: 'Fanta Zero', en: 'Fanta Zero', uk: 'Fanta Zero' },
    description: { nl: 'Orange Zero Sugar', en: 'Orange Zero Sugar', uk: 'Апельсин без цукру' },
    meta: { nl: '0,33 l', en: '0.33 L', uk: '0,33 л' },
    price: 250,
    image: '/menu/drinks/fanta-zero.jpg',
  },
];
