import { chromium } from '@playwright/test';
import {mkdir} from 'node:fs/promises';
const baseUrl=process.env.BASE_URL||'http://localhost:3000';
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1050},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(baseUrl,{waitUntil:'networkidle'});
await mkdir('artifacts',{recursive:true});
await page.screenshot({path:'artifacts/home-desktop.png',fullPage:false});
console.log('title',await page.title(),'products',await page.locator('.product-card').count());
await page.getByRole('combobox').click();
await page.getByRole('option',{name:'English',exact:true}).click();
await page.getByRole('heading',{name:'GOOD FOOD. GOOD MOOD.'}).waitFor();
const add=page.getByRole('button',{name:'Add to basket Philadelphia with shrimp',exact:true});
await add.click();await page.waitForTimeout(1400);await add.click();
await page.getByRole('button',{name:'Your basket: 2',exact:true}).click();
await page.getByRole('dialog').waitFor();
console.log('cart',await page.locator('.drawer-bottom').innerText());
await page.screenshot({path:'artifacts/cart-desktop.png'});
await page.getByRole('link',{name:'Checkout',exact:true}).click();
await page.getByRole('button',{name:'Pickup',exact:true}).click();
await page.getByLabel('Full name',{exact:true}).fill('Test Customer');
await page.getByLabel('Email address',{exact:true}).fill('customer@example.test');
await page.getByLabel('Phone number',{exact:true}).fill('+31600000000');
console.log('checkout unavailable',await page.getByRole('button',{name:'Continue to payment',exact:true}).isDisabled());
await page.screenshot({path:'artifacts/checkout-desktop.png',fullPage:true});
await page.reload({waitUntil:'networkidle'});
console.log('persisted cart',await page.locator('.cart-count').innerText());
await page.setViewportSize({width:390,height:844});
await page.goto(baseUrl,{waitUntil:'networkidle'});
await page.screenshot({path:'artifacts/home-mobile.png',fullPage:false});
console.log('mobile overflow',await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth));
await page.getByRole('combobox').click();
await page.getByRole('option',{name:'Українська',exact:true}).click();
console.log('uk heading',await page.locator('h1').innerText());
await page.locator('#menu').scrollIntoViewIfNeeded();
await page.screenshot({path:'artifacts/menu-mobile.png',fullPage:false});
await page.getByRole('textbox',{name:'Знайдіть улюблені суші...'}).fill('xyznotaproduct');
console.log('search empty',await page.getByText('Страв не знайдено. Спробуйте інший запит.').isVisible());
console.log('page errors',errors);
await browser.close();if(errors.length)process.exitCode=1;
